### ISSUE TITLE
Iniciar conversar com o IESB para possível local

### ISSUE THREAD

**Issue by taniaa** [pythoncerrado/organizacao-pycerrado2018#1]
(by @gilsondev)
Efetuar as conversas para um local que encaixe no seguinte perfil de evento:

    1 auditório para uso geral, como aberturas e fechamentos do evento e também palestras
    1 sala para palestras (no mínimo)
    1 sala para openspaces e uso da Pyladies

**Comment by taniaa** [comment]
Resumo da visita de hoje com a Patrícia.

Seria apoio ao evento, sem custo adicional, com contra partida de ter logo do IESB na camiseta, nos materiais de divulgação e banners do evento e desconto pros alunos.

Infra disponível:

- Bloco D: Auditório pra 500 pessoas com telão e telas no meio replicando o telão.
- Bloco B: 5 salas para 30 pessoas, 2 salas para 150 pessoas e 1 sala para 70 pessoas.
- Bloco J: Labs pra 40 pessoas ou 1 lab para 58 pessoas.
- Cantina Mega Matte - Abre sexta das 7h às 22h30 noite.
Sábado até 16/17h.

**Comment by gilsondev** [comment]
Segue o link com as informações do local e fotos tiradas durante a visita:

https://drive.google.com/drive/u/1/folders/1Sd6x7NKrr5SBHDCQT8gBe80pIWJBrJz7

**Comment by gilsondev** [comment]
Marcar próximo encontro com a Patrícia para alinhar os seguintes assuntos:

- [ ] Reserva do dia de domingo e o pagamento de funcionários do IESB para abertura do local e controle de som
- [ ] Espaço no IESB para Stands e Credenciamento
- [ ] Conclusão das salas desmembradas (bloco B com reforma da sala ou bloco C que é maior)
- [ ] Definição de Apoio ou patrocinio Platina em relação ao IESB

**Comment by taniaa** [comment]
Não esquecer de revisar melhor local para Open Space, dada a nova realocação de salas: https://github.com/pythoncerrado/organizacao-pycerrado2018/issues/21

**Comment by taniaa** [comment]
Por não terem disponível o Domingo, declinamos o convite.
