### ISSUE TITLE
Inscrições

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#16]
É importante termos um sistema de inscrições para centralizar o pagamento dos ingressos feito pelos participantes, quais descontos feitos e também algo que agilize o credenciamento dos mesmos. Os itens abaixo precisam ser feito para concluir a issue:

 - [ ] Conversar com outros organizadores dos eventos regionais, suas experiências com determinados sistemas
 - [ ] Avaliar os diferenciais de cada um e verificar o que encaixa melhor
 - [ ] Criar conta para ter acesso e preparar a solução antes do período de inscrições
 - [ ] Data de abertura/encerramento das inscrições / virada de lote

**Comment by Dayof** [comment]
Sugestões : 
- Eventbrite 
- Sympla

**Comment by Dayof** [comment]
Início das inscrições: Junho-Agosto/2018
- 1º Lote: 01 de Junho - 30 de Junho
- 2º Lote: 01 de Julho - 31 de Julho
- Virada do Lote: 30 de Junho

**Comment by hugoseabra** [comment]
Pessoal, tem a Congressy também: https://congressy.com

Exemplo do hotsite do evento:

https://ev.congressy.com/1o-meetup-de-startups-juridicas-oabgo/

**Comment by taniaa** [comment]
Inscrições abertas a algum tempo aqui: https://ev.congressy.com/python-cerrado/
