### ISSUE TITLE
Definir o local do evento

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#19]
Nessa issue vamos centralizar informações acerca da busca, visita e escolha definitiva para o Python Cerrado. Os locais em potencial até o momento são:

 - [IESB](https://github.com/pythoncerrado/organizacao-pycerrado2018/issues/1)
 - [CEUB](https://github.com/pythoncerrado/organizacao-pycerrado2018/issues/22)
 - [UnB](https://github.com/pythoncerrado/organizacao-pycerrado2018/issues/23)

É necessário concluir todos os itens abaixo para finalizar a issue:

 - [x] Visitar os locais levantados
 - [x] Registrar as características de cada uma de acordo com as necessidade já levantadas do evento
 - [x] Repassar informações necessárias para o local escolhido
 - [ ] Preparar contrato entre a APyB e o local escolhido para o evento
 - [ ] Efetuar a assinatura entre as partes (organização e representante do local)

**Comment by Dayof** [comment]
- Ceub
  - Fotos : No drive, na pasta [Python Cerrado 2018 > Escolha dos Locais > CEUB > fotos_visita](https://drive.google.com/drive/u/0/folders/1-CASN9NcRT4TJSg_7swmoj1-oZ4jWLcA)
  - Informações : No drive, na pasta [Python Cerrado 2018 > Escolha dos Locais > CEUB > descrição](https://docs.google.com/document/d/1h77ozK_Tos0utGeGox4xOzBF0a_5LRnK-77-hMGzOhs/edit?usp=sharing)

**Comment by taniaa** [comment]
Local definido:

Universidade de Brasília - Campus Gama
St. Leste Projeção A - Gama Leste, Brasília - DF
