### ISSUE TITLE
Orçar técnico de som para os dias do evento

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#20]
Durante o evento, é importante ter um técnico de som auxiliando em situações que o áudio não está bom, como também evitar o manuseio inadequado de equipamentos alugados ou cedidos pelo local. Dessa forma, precisamos levantar orçamento de técnicos que pode nos auxiliar nos locais que usam dos equipamentos durante os dias do evento.

**Comment by taniaa** [comment]
Talvez o ideal seria pagar as horas extras dos funcionários do IESB, como já conversamos antes. Só não tirar isso do radar ;)

**Comment by Dayof** [comment]
Podemos fechar já que no Ceub são técnicos da entidade mesmo ?

**Comment by taniaa** [comment]
Não sendo mais IESB, por conta do Domingo, sim...
