### ISSUE TITLE
Finalizar Proposta para Patrocinadores

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#24]
Nessa issue vamos centralizar as informações acerca da elaboração do documento de proposta para os patrocinadores, ajudando no entendimento do evento e seu propósito, como pacotes em que poderá aderir para auxiliar financeiramento evento, em troca de algumas coisas pontuados no mesmo. É necessário concluir os itens abaixo para fechar a issue:

 - [x] Elaborar a primeira versão da proposta aos patrocinadores
 - [x] Elaborar slides pra apresentação dos patrocínios 
 - [x] Efetuar a revisão juntamente com a organização
 - [ ] Lançar a versão definitiva e usar como meio de informação durante a conversa com possíveis patrocinadores

Segue o link do documento usado para definir o documento de proposta:
https://docs.google.com/document/d/107V-AEnn4AFBL0zDk8JrQk4dh81mwBrGSc04BFa3vSg/edit

**Comment by Dayof** [comment]
No drive, [Pacotes de patrocínio](https://docs.google.com/document/d/1WjIcCPiIAoBWrEFRsgzFM2FC-EHTe9p5IJY3Kcj6V7g/edit?usp=sharing)

**Comment by taniaa** [comment]
Revisei o doc de Patrocínio. Falta muito pouca coisa em amarelo para fechar:
1) Terá tutoriais? Como foi no local visitado? @Dayof 
2) Quantidade máxima? 200 ou chega a 250?
3) Local? O CEUB fechou?
4) Vamos criar Instagram? Senão só tirar...
5) Verificar mais eventos possíveis de divulgação...
6) Inserir os pacotes @Dayof 
7) Contatos. Coloquei só do gilson. @gilsondev quer por o meu??

**Comment by taniaa** [comment]
**Fechamos o doc:**

1. Terá tutoriais? Como foi no local visitado? Sim #17 
2. Quantidade máxima? 200 ou chega a 250? 240
3. Vamos criar Instagram? Não
4. Inserir os pacotes @Dayof - OK
5. Contatos - todos inseridos

**Pendente:**

1. Local? O CEUB fechou? Enviaremos doc formal pra confirmar
2. Verificar mais eventos possíveis de divulgação...

Doc de Apoio ao CEUB (que será base pro DOC de patrocínio depois):
https://docs.google.com/document/d/1ffdjECJ7EoAvxxKMN6Tijkvmd0rTX-pIsX_ePYZxMeY/edit#

Slides para apresentação dos patrocínios: https://docs.google.com/presentation/d/1CweS6eu3QDFG34DU1mLuGpyYnG6OWK_AbWlbSvsEdS4/edit#slide=id.p10

**Comment by taniaa** [comment]
Doc de patrocínio finalizado. Pasta com toda documentação de patrocínio: https://drive.google.com/drive/u/0/folders/1xQCeYTeOYdbXsilkbK_wqJmFvx7eQqcJ
