### ISSUE TITLE
Registrar domínio

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#25]
O site do evento precisa estar associado ao domínio como pythoncerrado.org. Dessa forma, o [site](https://github.com/pythoncerrado/pycerrado2018) desse ano poderia ser acessado como: http://2018.pythoncerrado.org

**Comment by gilsondev** [comment]
O domínio está disponível. Fiz uma pesquisa no namecheap.com:

![image](https://user-images.githubusercontent.com/265653/35239141-c5e71586-ff96-11e7-8a6a-6e2bed2b5e33.png)

**Comment by taniaa** [comment]
Falei com o Renato Oliveira e Ximenes pra saber como resolveram o domínio da Python Nordeste... Eles me indicaram falar com o Fabio Cerqueira. O adicionei no Hangout dia 16/Jan mas ainda não tive retorno. Então hoje mandei no Telegram da APyB pra ver se dão uma luz sobre isso.

**Comment by gilsondev** [comment]
Ok. Então vou atualizar a pauta da reunião

**Comment by taniaa** [comment]
Pela APyB teria que mandar email na lista APyB-condir, o Humberto faria o setup apontando pro local desejado (precisaria dizer se é uma entrada de tipo A ou CNAME) e onde o site estaria hospedado. A URL seria: cerrado.python.org.br

Como por unanimidade no debate do Telegram preferiram manter o que a Python Nordeste e Python Sudeste fizeram, o domínio será *PythonCerrado.org* mesmo
