### ISSUE TITLE
Criar site do evento

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#26]
Iniciar a construção do site do evento, em que possam disponibilizar as informações abaixo:

 - Data do evento
 - Local
 - Valor do ingresso

O layout é bom seguir as cores usadas na [logo](http://associacao.python.org.br/associacao/imprensa/logomarcas/python-cerrado), mas podemos discutir mais sobre isso e mais aqui.

**Comment by taniaa** [comment]
Site em desenvolvimento. Layout aprovado dia 20/Jan. Aguardo confirmação da sala e 2 keynotes pelo menos pra lançar com isso.

**Comment by taniaa** [comment]
Todos keynotes aprovados. Aguardamos apenas a confirmação da Patrícia (IESB) quanto ao domingo.

**Comment by taniaa** [comment]
Dia 10/abril mandei PR do site v.1 com o básico de info que temos e layout no github. E @gilsondev fez o merge. 

Diminui a descrição de cada Keynote, mas o ideal seria que ficassem mais ou menos do mesmo tamanho :/ Dificil... 

Não subi as fotos dos keynotes. Tem que tratar.

Mas o site já pode ir pro ar mesmo sem definirem o local...

**Comment by taniaa** [comment]
Como o @gilsondev comprou o domínio e colocou o site no ar estes dias, vou fechar esta issue e abrir outras de ajustes pontuais ;)

Ficou definido na reunião de hoje que divulgaremos o site nas redes sociais quando publicarmos todas as Keynotes.

http://2018.pythoncerrado.org/
