### ISSUE TITLE
Definir desconto dos ingressos

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#27]
Descontos dos ingressos do evento, que a princípio foi pensado:

 - Estudantes do local escolhido para o evento: 60 ingressos com 50% de desconto 
 - Associação Python Brasil: sem limite com 50% de desconto

**Comment by Dayof** [comment]
Sugestão : 
- 30 ingressos gratuitos para alunos do IESB (local do evento)
- 50% de gratuidade para associados da APYB / estudantes / PyLadies
- Possíveis para patrocinadores

**Comment by taniaa** [comment]
Fechamos em reunião hoje que o melhor é negociar 15 ingressos para CEUB, podendo chegar a 30 em negociação.

**Comment by alexandrebarbaruiva** [comment]
Ingressos acordados em R$25 para pagar kit de participante
