### ISSUE TITLE
Reservar local do Workshop extra do keynote Masanori

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#28]
- [ ] Infraestrutura: Reservar um local para suportar 30 a 40 pessoas, com suporte a internet. Importante alocar um local fora do evento.
- [ ] Staff: Monitores do workshop (Talitha, Alexandre e Fabiana)
- [ ] Material audiovisual: Datashow e projetor

**Comment by taniaa** [comment]
O grupo de Telegram é o mesmo do curso de dados anterior, ocorrido dia 18 Nov 2017. Se mais alguém for ajudar, me fala, pois sou admin.

**Comment by marcosvafg** [comment]
Além do que está listado não precisa ter tomadas na sala suficiente para o notebook de todo mundo que vai fazer o curso? Ou vamos levar extensões?

**Comment by taniaa** [comment]
@marcosvafg o Masanori já tem um “kit curso” que inclui isso ;)

**Comment by gilsondev** [comment]
Sala solicitada. Aguardando confirmação do pedido.

**Comment by taniaa** [comment]
O Masanori não poderá vir mais. O assunto do Keynote dele será tratado pela Judite.
