### ISSUE TITLE
Estimar quantidade de camisetas

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#3]
Definirmos a quantidade de camisetas e chegarmos em um número a serem providenciadas, e assim ajudar na busca dos orçamentos:

 - Staff
 - Participantes
 - Palestrantes
 - Patrocinadores

**Comment by alexandrebarbaruiva** [comment]
Quantidade de camisetas definida para 24, somente voluntários para organização receberão camisas.
