### ISSUE TITLE
Keynotes do Evento

### ISSUE THREAD

**Issue by gilsondev** [pythoncerrado/organizacao-pycerrado2018#9]
Durante os encontros principais, foi levantado a possibilidade de convidarmos pessoas para serem keynotes. Dessa forma precisamos concluir as etapas abaixo para concluir essa issue:

- [x] Selecionar possíveis keynotes do evento
- [x] Escolher os keynotes
- [ ] Verificar a possibilidade de ajuda no transporte a hospedagem
- [ ] Confirmar a vinda dos keynotes a mais ou menos um mês antes do evento

**Comment by Dayof** [comment]
Sugestões : 
- Luciano Ramalho (https://br.linkedin.com/in/lucianoramalho)
- Fernando Masanori (https://br.linkedin.com/in/fmasanori)

**Comment by Dayof** [comment]
Raquel Pereira
- Link : 
- Cidade : Goiânia
- Estado : A confirmar (@hugoseabra)

João Neto
- Link : https://www.linkedin.com/in/jo%C3%A3o-neto/
- Cidade : Goiânia
- Estado : Convite aceito (@hugoseabra)

Fernando Masanori
- Link : https://www.linkedin.com/in/fmasanori
- Cidade : São Paulo
- Estado : Confirmado #28 (@gilsondev)

Luciano Ramalho
- Link : https://ramalho.org
- Cidade : São Paulo
- Estado : Confirmado (@taniaa)

Rafahela Bazzanella
- Link : https://www.linkedin.com/in/rafahela/
- Cidade : Brasília
- Estado : A confirmar (@taniaa)

Edward Ribeiro
- Link : https://www.linkedin.com/in/edward-ribeiro-6530b82/
- Cidade : Brasília
- Estado : Confirmado (@tapumar)

João Eriberto Mota Filho
- Link : http://eriberto.pro.br/curriculo/
- Cidade : Brasília
- Estado : Convite aceito (@taniaa)

**Comment by taniaa** [comment]
Convite ao Eriberto, feito.

**Comment by taniaa** [comment]
@gilsondev @hugoseabra @tapumar favor solicitar foto e mini bio dos keynotes pelo qual estão responsáveis. Relacionado com: #26

**Comment by hugoseabra** [comment]
Feito. Logo posto.

Em sáb, 3 de mar de 2018 08:44, Tânia Andrea <notifications@github.com>
escreveu:

**Comment by taniaa** [comment]
João Eriberto Mota Filho é Oficial de Cavalaria do Exército
Brasileiro, atualmente na reserva. Foi gerente de rede e de segurança
em redes no Exército por 15 anos. É professor de pós-graduação em
diversas instituições de ensino. Autor dos livros Linux & Seus
Servidores (2000), Pequenas Redes com Microsoft Windows (2001),
Descobrindo o Linux (3ª edição em 2012) e Análise de tráfego em redes
TCP/IP (2013). Desenvolvedor Debian. Membro do time de Forense do
Debian.

**Comment by taniaa** [comment]
Luciano Ramalho é consultor na ThoughtWorks e autor do livro Fluent Python (O’Reilly, 2015), traduzido para 7 idiomas inclusive o português. Foi co-fundador da Associação Python Brasil e do Garoa Hacker Clube, o primeiro hackerspace do país.

**Comment by tapumar** [comment]
Edward Ribeiro é mestre em Informática e Bacharel em Ciências da Computação pela Universidade de Brasília. Lecionou em faculdades particulares do DF entre 2002 e 2008, e como professor substituto na UnB. Desde 2007 desenvolve projetos como pesquisador associado em conjunto com o grupo de sistemas distribuídos da UnB, tendo várias publicações nacionais e internacionais. Trabalhou com desenvolvimento de sistemas no SERPRO, STM, TSE, Câmara Legislativa do DF (CL-DF) e na empresa DataStax, responsável pelo banco de dados Cassandra. Atualmente trabalha no programa Interlegis do Senado Federal, onde desenvolve sistemas web em Django e Python, que são usados por 700 municípios do Brasil.

**Comment by hugoseabra** [comment]
João José Ribeiro Neto, atualmente trabalhando como Analista de Segurança da Informação no Instituto de Assistência dos Servidores Públicos do Estado de Goiás - IPASGO, pós graduado no curso de Redes de Computadores e Segurança de Sistemas pela UFG, graduado no curso Tecnólogo em Segurança da Informação pela Faculdade SENAC, Certificado ISO 27002 Foundation pela EXIN, usuário Debian e acredita que o conhecimento foi feito para ser compartilhado.

**Comment by taniaa** [comment]
@gilsondev falta a mini bio do Masanori.

**Comment by taniaa** [comment]
Solicitei a mini bio e foto pro Masanori agorinha.

**Comment by taniaa** [comment]
Fernando é professor da FATEC São José dos Campos, adora dar aulas, graduado em Computação pelo IME-USP, mestrado pelo ITA. Já desenvolveu projetos para Credicard Mastercard e Itaú BankBoston. Nos dois últimos anos deu mais de cem palestras e minicursos, na comunidade Python, viajando pelo Brasil e outros quinze países. É o criador do Python para Zumbis http://pycursos.com/python-para-zumbis/
Participa, como representante da América Latina, do Grants Work Group, que aprova todos os pedidos de financiamento para workshops e conferências Python no mundo.
No final de 2017 foi nomeado Fellow da PSF, pelas contribuições ao crescimento da comunidade Python no Brasil.
Em 2017 tem feito um esforço especial para divulgação de Python para o Jornalismo de Dados.
Ministrou cursos para jornalistas na Editora Abril, Folha de SP e LabJor Unicamp. E para o público geral em Maceió (OxE Hacker Clube), Salvador (Raul Hacker Clube), São Paulo (Coletivida), Manaus (Coletivo Difusão), USP São Carlos, Federal de São Carlos, UDESC Joinville. Totalizou 26 workshops dedicados à jornalistas no segundo semestre de 2017.
Os contatos dele você encontra em https://about.me/fmasanori
https://www.python.org/psf/fellows/
https://wiki.python.org/psf/GrantsWG/Charter

**Comment by Dayof** [comment]
Aberto novamente para incluir as Keynotes :smiley:

**Comment by taniaa** [comment]
A Renata do PyLadies POA sugeriu estas:
- mulher cega que trabalha com TI e vem pro RS ajudar com inclusão no Django Girls Canoas;
- @andrezarocha_rh que puxa o AfroPython;
- @contraexemplo que foi estagiária do Outreachy e pode falar sobre documentação e acessibilidade (ver se tem perfil de Keynote);
- Greice de poa, que foi treinadora de DG e AfroPython (ela trabalha com Python e Django há meses).

**Comment by taniaa** [comment]
Também cogitamos @dayof, @tspumar e @taniaa, mas estamos na organização do evento... não sabemos se convém :/

**Comment by taniaa** [comment]
Local e data do evento precisaram ser mudadas. Abaixo está a lista dos keynotes oficiais:

**Edward Ribeiro**
Desenvolvedor no Interlegis

Edward Ribeiro é mestre em Informática e Bacharel em Ciência da Computação pela Universidade de Brasília. Trabalha no programa Interlegis do Senado Federal, onde desenvolve sistemas web em Django e Python, que são usados por 700 municípios do Brasil. Lecionou em faculdades particulares do DF entre 2002 e 2008, e como professor substituto na UnB. Desde 2007 desenvolve projetos como pesquisador associado em conjunto com o grupo de sistemas distribuídos da UnB, tendo publicações nacionais e internacionais. Trabalhou com desenvolvimento de sistemas no SERPRO, STM, TSE, Câmara Legislativa do DF (CL-DF) e na empresa DataStax, colaborando com o banco de dados Cassandra.

**Raquel Pereira**
Analista de Sistemas

Raquel Pereira é analista de sistemas há 7 anos com experiência em sistemas ERP´s, é graduanda em Sistemas de Informações pelo IFG Goiânia. Participante ativa em comunidades e eventos de tecnologia. Colaboradora nos eventos: Latinoware, Fórum Goiano de Software Livre e Women Techmakers Goiânia. Aprendiz Jedi e entusiasta em Data Science, acredita no poder de aprender e reaprender constantemente.

**Judite Cypreste**
Repórter do Aos Fatos

Judite Cypreste é repórter do Aos Fatos. Formada em letras pela PUC-RJ, está no 8º semestre de jornalismo na Uerj, onde também cursa pós-graduação em jornalismo cultural. Ex-trainee de jornalismo de dados da Folha de S.Paulo, realizou reportagens usando Python e raspagens de dados. É também autora do Projeto Coração Radiante, onde fez análise de sentimentos dos torcedores brasileiros durante a Copa do Mundo.
